export enum EServerRequest {

    POSITION_UPDATE = 2,
    GRAPPLING_POSITION,
    FLIP,
    PING,
    PLAYER_HIT,
    PLAYER_EXPLOSION_HIT,
    ABILITY_CAST,
    PROJECTILE_UPDATE,
    ENTITY_UPDATE,
    ENTITY_HIT

}

export enum EServerResponse {

    PLAYER_JOIN = 1,
    PLAYER_UPDATE,
    PLAYER_GRAPPLE,
    PLAYER_FLIP,
	PLAYER_HIT,
	PLAYER_ABILITY_CAST,
    PLAYER_FORCED_DASH,
	
	EFFECT_ADD,
	
    PING,
    
    PROJECTILE_CREATE,
    PROJECTILE_UPDATE,
    PROJECTILE_DESTROY,
    
    EXPLOSION_CREATE,
    
	ENTITY_CREATE,
    ENTITY_UPDATE,
    ENTITY_DESTROY

}