export enum REQUEST {

    POSITION_UPDATE = 2,
    GRAPPLING_POSITION,
    FLIP,
    PING,
    PLAYER_HIT,
    PLAYER_EXPLOSION_HIT,
    ABILITY_CAST,
    PROJECTILE_UPDATE,
    ENTITY_UPDATE,
    ENTITY_HIT

}

export enum RESPONSE {

    PLAYER_JOIN = 1,
    PLAYER_UPDATE,
    PLAYER_GRAPPLE,
    PLAYER_FLIP,
    PING,
    PROJECTILE_CREATE,
    PLAYER_HIT,
    PROJECTILE_DESTROY,
    PLAYER_ABILITY_CAST,
    EFFECT_ADD,
    EXPLOSION_CREATE,
    PROJECTILE_UPDATE,
    ENTITY_UPDATE,
    ENTITY_DESTROY

}