export enum EServerRequest {

    IDENTIFY,
    POSITION_UPDATE = 2,
    GRAPPLING_POSITION,
    FLIP,
    PING,
    PLAYER_HIT,
    PLAYER_EXPLOSION_HIT,
    ABILITY_CAST,
    PROJECTILE_UPDATE,
    ENTITY_UPDATE,
    ENTITY_HIT

}

export enum EServerResponse {

    PREMATCH,

    GAME_STATE,

    PLAYER_CREATE,
    PLAYER_CONNECTION,
    PLAYER_UPDATE,
    PLAYER_GRAPPLE,
    PLAYER_FLIP,
    PLAYER_HIT,
    PLAYER_ABILITY_CAST,
    PLAYER_FORCED_DASH,
    PLAYER_DEATH,

    EFFECT_ADD,

    PING,

    PROJECTILE_CREATE,
    PROJECTILE_UPDATE,
    PROJECTILE_DESTROY,

    EXPLOSION_CREATE,
    
	ENTITY_CREATE,
    ENTITY_UPDATE,
    ENTITY_DESTROY

}

export enum EServerResponsePreMatch {

    MATCH_NOT_FOUND,
    MATCH_ENDED,
    REJOINED,
    IDENTIFIED,
    PLAYER_LOADED,
    MATCH_STARTING,
    MATCH_STARTED

}